apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jk
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    env:
        - name: JENKINS_OPTS
          value: --prefix=/jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-clusterip
spec:
  selector:
    app: jk
  ports:
    - name: jenkins
      protocol: TCP
      targetPort: 8080
      port: 8080
