apiVersion: v1
kind: Service
metadata:
  name: tomcat-nginx-nodeportservice
spec:
  selector:
    app: tomcat-nginx-pd
  type: NodePort
  ports:
    - name: tomcat-port
      protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 31999 
    - name: nginx-port
      protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 31050
