apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-nginx-deployment
  namespace: myspace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-nginx-pd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: tomcat-nginx
      labels:
        app: tomcat-nginx-pd
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - tomcat-nginx-pd
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: apache-tomcat
          image: krishna123456/tomcat:1.11.111
