kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claimr
  namespace: myspace
  labels:
    type: amazonEBS
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: test2
