apiVersion: v1
kind: Service
metadata:
  name: tomcat-nginx-service
spec:
  selector:
    app: tomcat-nginx-pd
  type: ClusterIP
  ports:
    - name: tomcat-port
      protocol: TCP
      targetPort: 8080
      port: 8080
    - name: nginx-port
      protocol: TCP
      targetPort: 80
      port: 80

