---
# Source: helm-prac/templates/clusterIP-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  selector:
    app: tomcat
  type: ClusterIP
  ports: 
    - name: tomcat
      protocol: TCP
      targetPort: 8080
      port: 8080
---
# Source: helm-prac/templates/tc-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-tc
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: krishna123456/tomcat:1.11.111
