apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jenkins-daemon-vol
  namespace: myspace
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          volumeMounts:
            - mountPath: "/var/jenkins_home"
              name: "jenkin-data"
      volumes:
        - name: "jenkin-data"
          hostPath:
            path: "/opt/efs"
