apiVersion: v1
kind: Pod
metadata:
  name: tomcat-nginx
  namespace: {{ .Values.selector_label }}
  labels:
    app: tomcat-nginx-pd
spec:
  containers:
    - name: apache-tomcat
      image: krishna123456/tomcat:1.11.111

